version: "3.7"

volumes:
    prometheus_data: {}
    grafana_data: {}
    cadvisor_data: {}
    node_exporter_data: {}
    sqlite: {}

networks:
  telegram-net:

services:

  redis:
    container_name: redis
    image: redis:latest
    stdin_open: true
    tty: true
    networks:
      - telegram-net
    restart: always

  telegrambot:
    container_name: telegramBot
    image: ivaneyukin/telegram:1.0.5
    volumes:
      - sqlite:/project/telegrambot/db
    networks:
      - telegram-net
    ports:
      - 9900:9900
    restart: always

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.45.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.size=1GB'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    ports:
      - 8090:9090
    depends_on:
      - cadvisor
    networks:
      - telegram-net
    restart: always

  node-exporter:
    container_name: node-exporter
    image: quay.io/prometheus/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - node_exporter_data:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 8091:9100
    networks:
      - telegram-net
    restart: always

  redis-exporter:
    container_name: redis-exporter
    image: oliver006/redis_exporter:alpine
    command: ["--redis.addr", "redis://redis:6379"]
    ports:
      - "6060:9121"
    networks:
      - telegram-net
    restart: always

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager
    ports:
      - 8092:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    networks:
      - telegram-net
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: always

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - cadvisor_data:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8093:8080
    networks:
      - telegram-net
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 8094:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    networks:
      - telegram-net
    user: "472"
    restart: always