{
 "title": "Redis",
 "description": "Redis",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_uptime_in_seconds" }
   ]
  },
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_connected_clients" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image=\"redis:latest\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{image=\"redis:latest\"}"
    }
   ]
  },
  {
   "title": "Sum Keys",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(redis_db_keys)" }
   ]
  },
  {
   "title": "Memory Usage Dataset",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_memory_used_dataset_bytes"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total[1m])"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "redis_keyspace_hits_total", "legendFormat": "hits" },
    {
     "expr": "irate(redis_keyspace_misses_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "redis_memory_used_bytes", "legendFormat": "used" }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(redis_db_keys) - sum(redis_db_keys_expiring) ",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum (redis_db_keys_expiring{instance=~\"$instance\"}) ",
     "legendFormat": "expiring"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum (redis_db_keys)", "legendFormat": "{{ db }} " }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total[1m])",
     "legendFormat": "input"
    },
    {
     "expr": "rate(redis_net_output_bytes_total[1m])",
     "legendFormat": "output"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total[1m]))",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{instance=~\"$instance\"}[5m])) by (instance)",
     "legendFormat": "evicted"
    }
   ]
  },
  {
   "title": "Redis connected clients",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "redis_connected_clients" }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, irate(redis_commands_total[1m]))",
     "legendFormat": "{{ cmd }}"
    }
   ]
  }
 ]
}